import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Faixa Rosa",
  description: "Generated by create next app",
};

const DynamicSearchLayout = dynamic(() => import('./searchLayout'), {
  ssr: false
})

export default function SearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <DynamicSearchLayout />
    </>
  );
}
