import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MoreCompanions from "./(profileComponents)/MoreCompanions";
import GoogleBanner from "./(profileComponents)/GoogleBanner";
import LayoutTabs from "./layoutTabs";
import ProfileHeader from "./profileHeader";
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Faixa Rosa | Perfil",
	description: "Generated by create next app",
};

const DynamicProfileHeader = dynamic(() => import('./profileHeader'), {
	ssr: false
})

export default async function ProfileLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			style={{
				marginTop: "40px",
			}}
			className="container"
		>
			<div className="row g-4">
				<div className="col-lg-8 vstack gap-4">
					<div className="card">
						<div>
							{/* Cover image */}
							<DynamicProfileHeader />
							{/* Card body END */}
							<LayoutTabs />
							{/* My profile END */}
						</div>
					</div>
					{children}
					{/* <Outlet /> */}
				</div>
				<div className="col-lg-4 vstack gap-4">
					<MoreCompanions />
					<GoogleBanner />
				</div>
			</div>
		</div>
	);
}
